"""Formatter for discovered registry skills.

Reads an aggregate manifest generated by the registry discovery extension and
prints human-readable or JSON output.
"""

import json
import os
import sys


def _load_manifest(manifest_path):
    """Load the aggregate manifest from the given path."""
    if not os.path.isfile(manifest_path):
        print("error: manifest not found at %s" % manifest_path, file=sys.stderr)
        return None
    with open(manifest_path) as f:
        return json.load(f)


def _parse_args(argv):
    """Parse CLI flags from argv."""
    opts = {"json": False, "registry": None, "skill": None, "agent": None}
    for arg in argv:
        if arg == "--json":
            opts["json"] = True
        elif arg.startswith("--registry="):
            opts["registry"] = arg[len("--registry="):]
        elif arg.startswith("--skill="):
            opts["skill"] = arg[len("--skill="):]
        elif arg.startswith("--agent="):
            opts["agent"] = arg[len("--agent="):]
        else:
            print("error: unknown flag %s" % arg, file=sys.stderr)
            return None
    return opts


def _filter_manifest(manifest, opts):
    """Apply filters to the aggregate manifest and return a filtered copy."""
    filtered_registries = []
    for registry in manifest.get("registries", []):
        if opts["agent"] and opts["agent"] not in registry.get("agents", []):
            continue
        if opts["registry"] and registry.get("id") != opts["registry"]:
            continue

        if opts["skill"]:
            matching_skills = [
                s for s in registry.get("skills", [])
                if s.get("skill_name") == opts["skill"]
            ]
            if not matching_skills:
                continue
            registry = dict(registry)
            registry["skills"] = matching_skills

        filtered_registries.append(registry)

    return {"version": manifest.get("version", 1), "registries": filtered_registries}


def _remote_stanza(registry):
    """Build the skill_deps.remote(...) Bazel snippet for a registry."""
    lines = [
        "skill_deps = use_extension(",
        '    "@rules_agents//rules_agents:extensions.bzl",',
        '    "skill_deps",',
        ")",
        "skill_deps.remote(",
        '    name = "%s",' % registry["id"],
        '    url = "%s",' % registry["archive_url"],
    ]
    if registry.get("strip_prefix"):
        lines.append('    strip_prefix = "%s",' % registry["strip_prefix"])
    if registry.get("skill_path_prefix"):
        lines.append('    skill_path_prefix = "%s",' % registry["skill_path_prefix"])
    lines.append(")")
    lines.append('use_repo(skill_deps, "%s")' % registry["id"])
    return "\n".join(lines)


def _print_human(manifest):
    """Print human-readable output grouped by registry."""
    registries = manifest.get("registries", [])
    if not registries:
        print("No skills discovered from configured registries.")
        return

    first = True
    for registry in registries:
        if not first:
            print()
        first = False

        print("Registry: %s" % registry["id"])
        print()
        print("Add:")
        for line in _remote_stanza(registry).splitlines():
            print("  %s" % line)

        for skill in registry.get("skills", []):
            print()
            print("- %s" % skill["skill_name"])
            if skill.get("description"):
                print("  Description: %s" % skill["description"])
            if skill.get("source_url"):
                print("  Source: %s" % skill["source_url"])
            print("  Target: %s" % skill["target_label"])


def _print_json(manifest):
    """Print the filtered aggregate manifest as JSON."""
    print(json.dumps(manifest, indent=2))


def main(manifest_path, argv):
    """Entry point called from the generated list_skills_main.py.

    Args:
        manifest_path: absolute path to aggregate_manifest.json.
        argv: CLI arguments (e.g. --json, --registry=..., --skill=..., --agent=...).

    Returns:
        Exit code (0 on success).
    """
    opts = _parse_args(argv)
    if opts is None:
        return 1

    manifest = _load_manifest(manifest_path)
    if manifest is None:
        return 1

    filtered = _filter_manifest(manifest, opts)

    if opts["json"]:
        _print_json(filtered)
    else:
        _print_human(filtered)

    return 0
